# Site settings
title: My Blog
email: christopher.jativa320@outlook.com
description: My simple blog.
baseurl: "/blog"
url: ""
twitter_username: 
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Christopher D Jativa" # Set default author name
      categories: "Computer Science"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
